title: "RAIN report"

run_modules:
    - fastqc
    - bowtie2
    - bwa 
    - bwa-mem
    - hisat2
    - star
    - picard/markdups
      
module_order:
    - fastqc:
        name: FastQC (raw)
        path_filters: 
            - "*logs_raw*"
    - bowtie2
    - bwa 
    - bwa-mem
    - hisat2
    - star
    - fastqc:
        name: FastQC (ali)
        path_filters: 
            - "*logs_ali*"
    - picard/markdups
    - fastqc:
        name: FastQC (markDuplicates)
        path_filters: 
            - "*logs_dup*"
    - fastqc:
        name: FastQC (ClipOverlap)
        path_filters: 
            - "*logs_clip*"
sp:
  picard/markdups:
    fn: "*marked_dup_metrics.txt"